### ISSUE TITLE
Tabs in avengers theme.yml prevents loading theme

### ISSUE THREAD

**Issue by dmacduff** [gravityatom/make_theme#1]
## Summary
`make_theme.py` fails when run with `--theme avengers` due to tabs instead of spaces in yaml doc.

## Error trace:
```bash
sudo ./make_theme.py --theme avengers
Traceback (most recent call last):
  File "/home/demo/make_theme/./make_theme.py", line 514, in <module>
    theme_conf = yaml.load(f, Loader=yaml.FullLoader)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 449, in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 258, in fetch_more_tokens
    raise ScannerError("while scanning for the next token", None,
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "themes/avengers/theme.yml", line 9, column 1
```

## Fix
Replace all tabs with 2 spaces each.

**Comment by dmacduff** [comment]
I would add the label `bug` if I could.

I am working on this and a few other issues to get the Avengers theme up and running. I will submit Pull Request soon.
