### ISSUE TITLE
Missing password for Captain America

### ISSUE THREAD

**Issue by dmacduff** [gravityatom/make_theme#4]
## Summary
Creating admin users fails for Captain America because his password is not configured.

## Error trace

```bash
sudo ./make_theme.py --theme avengers
[...]
Adding user `captainamerica' ...
Adding new group `captainamerica' (1002) ...
Adding new user `captainamerica' (1002) with group `captainamerica' ...
Creating home directory `/home/captainamerica' ...
Copying files from `/etc/skel' ...
Traceback (most recent call last):
  File "/mnt/hgfs/make_theme/./make_theme.py", line 522, in <module>
    set_customizations(theme_conf)
  File "/mnt/hgfs/make_theme/./make_theme.py", line 59, in set_customizations
    create_admins(theme_conf['admins'])
  File "/mnt/hgfs/make_theme/./make_theme.py", line 363, in create_admins
    pwfile.write(userid + ":" + admins[userid]['password'] + "\n")
KeyError: 'password'
```

## Fix
Add `password: rogers123` to captainamerica dictionary

**Comment by dmacduff** [comment]
I would label this `bug` if I could.
